;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,182,151 ; New song

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$00,$03
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cf,$c8,$c0,$00,$02


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$30,$30,$30,$30,$30,$81,$24,$24
@ref1:
	.byte $24,$23,$23,$81,$2f,$2f,$2f,$2f
@ref2:
	.byte $30,$81,$30,$2f,$30,$2f,$30,$81
@ref3:
	.byte $30,$2f,$30,$2f,$30,$85
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $7f,$82,$1d,$7d,$81,$7b,$81,$79,$81,$77,$81,$73,$81,$71,$81,$70
	.byte $81
@ref5:
	.byte $7f,$1c,$7d,$81,$7b,$81,$79,$81,$77,$81,$73,$81,$71,$81,$70,$81
	.byte $ff,$08
	.word @ref5
@ref7:
	.byte $7f,$18,$7d,$81,$7b,$81,$79,$81,$77,$81,$73,$81,$71,$81,$70,$81
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $82,$24,$8d
@ref9:
	.byte $23,$8d
@ref10:
	.byte $21,$8d
@ref11:
	.byte $1f,$8d
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $84,$01,$06,$01,$06,$01,$06,$01,$06
@ref13:
	.byte $01,$06,$01,$06,$01,$06,$01,$06
	.byte $ff,$08
	.word @ref13
@ref15:
	.byte $01,$06,$01,$06,$01,$06,$80,$0d,$84,$06
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $8f
@ref17:
	.byte $8f
@ref18:
	.byte $8f
@ref19:
	.byte $8f
	.byte $fd
	.word @song0ch4loop
